FROM python:3.11.8-slim-bookworm

WORKDIR /veefyed
ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONBUFFERED=1

RUN apt-get update \
  && apt-get -y install netcat-openbsd gcc libpq-dev dos2unix  \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements-dev.txt /veefyed/
RUN pip install --upgrade -r requirements.txt -r requirements-dev.txt

COPY . /veefyed/

CMD ["/bin/sh", "-c", "dos2unix ./run_dev.sh && chmod +x ./run_dev.sh && ./run_dev.sh"]
